src/PeopleLink.PL/Web/Areas/Employee/Models/AdvanceViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web.Areas.Employee.Models
{
    public class AdvanceViewModel
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; } = null!;

        [Required(ErrorMessage = "Lütfen avans türünü seçiniz.")]
        public AdvanceType AdvanceType { get; set; }
        [Required(ErrorMessage = "Lütfen birim tutar giriniz.")]
        public decimal Amount { get; set; }
        [Required(ErrorMessage = "Lütfen para birimi giriniz.")]
        public Currency Currency { get; set; }
        public string Status { get; set; } = null!;
        public DateTime RequestDate { get; set; }
        public DateTime? ResponseDate { get; set; }
        [Required(ErrorMessage = "Lütfen açıklama giriniz.")]
        [StringLength(50, ErrorMessage = "Açıklama {2}-{1} arasında olmalıdır.", MinimumLength = 20)]
        public string Description { get; set; } = null!;
        public DateTime? ApprovalDate { get; set; }
    }
}

src/PeopleLink.PL/Web/Areas/Employee/Controllers/AdvanceController.cs
using ApplicationCore.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Web.Areas.Employee.Models;
using Microsoft.AspNetCore.Authorization;
using Web.Areas.Identity.Pages.Account;



namespace Web.Areas.Employee.Controllers
{
    [Area("Employee")]
    public class AdvanceController : Controller
    {
        private readonly HttpClient _httpClient;
        private UserManager<ApplicationUser> _userManager;

        public AdvanceController(HttpClient httpClient, UserManager<ApplicationUser> userManager)
        {
            _httpClient = httpClient;
            _userManager = userManager;

        }

        public async Task<IActionResult> AdvanceRequest()
        {
            var user = await _userManager.GetUserAsync(User);
            var advancetypes = Enum.GetValues(typeof(AdvanceType)).Cast<AdvanceType>().ToList();
            var currencyTypes = Enum.GetValues(typeof(Currency)).Cast<Currency>().ToList();

            ViewData["UserId"] = user.Id;
            TempData["Picture"] = (await _userManager.GetUserAsync(User))!.PictureUri;
            ViewData["Amount"] = user.AdvanceAllowance;
            ViewBag.AdvanceType = advancetypes;
            ViewBag.CurrentType = currencyTypes;
            NameMethod(user);
            return View();

            
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> AdvanceRequest(AdvanceViewModel advanceViewModel)
        {
            var user = await _userManager.GetUserAsync(User);
            ViewData["Amount"] = user.AdvanceAllowance;
            NameMethod(user);

            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                string apiUrl = $"https://peoplelinkapi1.azurewebsites.net/api/Advance?employeeId={userId}";

                var advances = await _httpClient.GetFromJsonAsync<List<AdvanceViewModel>>(apiUrl);

                var advanceId = advances!.Where(x => x.Status == advanceViewModel.Status && x.AdvanceType == advanceViewModel.AdvanceType).Select(x => x.Id).FirstOrDefault();

                if (advanceId != 0)
                {
                    TempData["HasPendingAdvance"] = "Onay bekleyen avans talebiniz bulunmaktadır.";
                    return RedirectToAction("AllAdvances");
                }
                else
                {
                    var advanceAmount = advanceViewModel.Currency == Currency.TL ? advanceViewModel.Amount
               : advanceViewModel.Currency == Currency.Dolar ? advanceViewModel.Amount * 27
               : (advanceViewModel.Currency == Currency.Euro ? advanceViewModel.Amount * 29 : advanceViewModel.Amount * 33);

                    if (advanceViewModel.AdvanceType == AdvanceType.Individual)
                    {
                        if (user!.AdvanceAllowance < advanceAmount)
                        {
                            TempData["HasPendingAdvance"] = $"Talep edebileceğiniz miktarı aştınız. Talep edebileceğiniz güncel tutar:{user.AdvanceAllowance}";
                            return RedirectToAction("AllAdvances");
                        }

                    }
                    else if (advanceViewModel.AdvanceType == AdvanceType.Corporate)
                    {
                        if (advanceViewModel.Currency == Currency.TL && advanceViewModel.Amount > 1000000)
                        {
                            TempData["HasPendingAdvance"] = $"1.000.000 {advanceViewModel.Currency} üzeri avans talepleri için lütfen yöneticinize başvurunuz.";
                            return RedirectToAction("AllAdvances");
                        }
                        else if (advanceViewModel.Currency != Currency.TL && advanceViewModel.Amount > 35000)
                        {
                            TempData["HasPendingAdvance"] = $"35.000 {advanceViewModel.Currency} üzeri avans talepleri için lütfen yöneticinize başvurunuz.";
                            return RedirectToAction("AllAdvances");
                        }
                    }

                    var resp = await _httpClient.PostAsJsonAsync("https://peoplelinkapi1.azurewebsites.net/api/Advance", advanceViewModel);

                    user.AdvanceAllowance = user.AdvanceAllowance - advanceAmount;
                    await _userManager.UpdateAsync(user);
                    ViewData["Amount"] = user.AdvanceAllowance;

                    TempData["SuccessAdvance"] = "Avans talebi başarıyla oluşturuldu.";
                    return RedirectToAction("AllAdvances");
                }

            }
            
            return View();
        }


        public async Task<IActionResult> AllAdvances(string? status)
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = _userManager.GetUserId(User);
            string apiUrl = $"https://peoplelinkapi1.azurewebsites.net/api/Advance?employeeId={userId}";
            string apiUrlWithStatus = $"https://peoplelinkapi1.azurewebsites.net/api/Advance?status={status}&employeeId={userId}";
            TempData["Picture"] = (await _userManager.GetUserAsync(User))!.PictureUri;
            ViewBag.Status = status;
            ViewBag.HasPendingAdvance = TempData["HasPendingAdvance"];
            ViewBag.SuccessAdvance = TempData["SuccessAdvance"];
            ViewBag.DeleteSuccessAdvance = TempData["DeleteSuccessAdvance"];
            NameMethod(user);

            if (status != null)
            {
                var advanceWithStatus = await _httpClient.GetFromJsonAsync<List<AdvanceViewModel>>(apiUrlWithStatus);

                if (advanceWithStatus != null)

                    return View(advanceWithStatus);
            }
            var advances = await _httpClient.GetFromJsonAsync<List<AdvanceViewModel>>(apiUrl);
            return View(advances);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAdvance(int advanceId)
        {
            var advance = await _httpClient.GetFromJsonAsync<AdvanceViewModel>($"https://peoplelinkapi1.azurewebsites.net/api/Advance/{advanceId}");
            var user = await _userManager.GetUserAsync(User);
            NameMethod(user);

            var advanceAmount = advance.Currency == Currency.TL ? advance.Amount
               : advance.Currency == Currency.Dolar ? advance.Amount * 27
               : (advance.Currency == Currency.Euro ? advance.Amount * 29 : advance.Amount * 33);

            user.AdvanceAllowance = user.AdvanceAllowance + advanceAmount;
            await _userManager.UpdateAsync(user);

            await _httpClient.DeleteAsync($"https://peoplelinkapi1.azurewebsites.net/api/Advance/{advanceId}");
            TempData["DeleteSuccessAdvance"] = "Avans talebi başarıyla silindi.";
            return RedirectToAction("AllAdvances");
        }

        private void NameMethod(ApplicationUser? user)
        {
            TempData["Name"] = user.FirstName + " " + (user.MiddleName != null ? user.MiddleName : "") + (user.MiddleLastName != null ? user.MiddleLastName : "") + " " + user.LastName;
            TempData["Picture"] = user.PictureUri;
        }
    }
}

src/PeopleLink.PL/Web/Areas/Employee/Views/Advance/AdvanceRequest.cshtml
@using ApplicationCore.Enums;

@model AdvanceViewModel

@{
    ViewData["Title"] = "Avans Talep Sayfası";
    var userId = ViewData["UserId"];
}

<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>Avanslar</h2>
        </div>
    </div>
</div>

<div class="white_shd full margin_bottom_30">
    <div class="full graph_head">
        <h2>Avans Talep Sayfası</h2>
        <div class="full price_table padding_infor_info">
            <hr>
            @if (ViewBag.HasPendingAdvance != null)
            {
                <div class="alert alert-danger">@ViewBag.HasPendingAdvance</div>
            }
            <div class="row">
                <div class="col-md-9">
                    <div class="row ">
                        <div class="col-md-8">
                            <form id="profile-form" method="post" enctype="multipart/form-data">
                                <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                                <div class="mb-3">
                                    <label asp-for="AdvanceType" class="form-label">Avans Türünü Seçiniz</label>
                                </div>
                                <select asp-for="AdvanceType" asp-items="@Html.GetEnumSelectList<AdvanceType>()" class="form-control">
                                    <option value="">Seçiniz</option>
                                </select>
                                <span asp-validation-for="AdvanceType" class="text-danger"></span>
                                <div class="row">
                                    <div class="col-md-6 mb-3">
                                        <label asp-for="Amount" class="form-label">Tutar:</label>
                                        <input asp-for="Amount" type="number" value="" class="form-control" />
                                        <span asp-validation-for="Amount" class="text-danger"></span>
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <label for="selectedCurrency" class="form-label">Para Birimi</label>
                                        <select asp-for="Currency" asp-items="@Html.GetEnumSelectList<Currency>()" class="form-control">
                                            <option value="" selected disabled>Seçiniz</option>
                                        </select>
                                        <span asp-validation-for="Currency" class="text-danger"></span>
                                    </div>
                                    <div class="col-md-12 mb-3">
                                        <label asp-for="Description" class="form-label">Açıklama</label>
                                        <textarea asp-for="Description" rows="2" class="form-control"></textarea>
                                        <span asp-validation-for="Description" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <input asp-for="EmployeeId" type="hidden" value="@userId" class="form-control" />
                                </div>

                                <div class="col-md-6 mb-3">
                                    <input asp-for="Status" type="hidden" value="Onay Bekliyor." class="form-control" />
                                </div>
                                <button id="update-profile-button" type="submit" class="main_bt read_bt w-100 btn btn-lg btn-primary">Talep Et</button>
                            </form>
                        </div>
                        <div class="col-md-4">
                            <div>
                                <label>Kalan Avans Tutarı: <strong>@(((decimal)ViewData["Amount"]) > 0 ? ((decimal)ViewData["Amount"]) : 0) ₺</strong></label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", function () {

            function calculateTotalDays() {

                var startingDateInput = document.getElementById("startingDate");
                var endingDateInput = document.getElementById("endingDate");
                var selectedLeaveType = document.getElementById("LeaveType").value;

                var startDate = new Date(startingDateInput.value);
                var endDate = new Date(startDate);

                if (selectedLeaveType == '1' || selectedLeaveType == '3') {

                    document.getElementById("totalDays").value = 3;

                    endDate.setDate(startDate.getDate() + 3);
                    var formattedEndDate = endDate.toISOString().slice(0, 10);
                    endingDateInput.value = formattedEndDate;
                }
                else if (selectedLeaveType == '4') {

                    document.getElementById("totalDays").value = 112;

                    endDate.setDate(startDate.getDate() + 112);
                    var formattedEndDate = endDate.toISOString().slice(0, 10);
                    endingDateInput.value = formattedEndDate;
                }
                else if (selectedLeaveType == '5') {
                    document.getElementById("totalDays").value = 5;

                    endDate.setDate(startDate.getDate() + 5);
                    var formattedEndDate = endDate.toISOString().slice(0, 10);
                    endingDateInput.value = formattedEndDate;
                }
                else {

                    var timeDifference = new Date(endingDateInput.value) - new Date(startingDateInput.value) - 1;
                    var totalDays = Math.ceil(timeDifference / (1000 * 3600 * 24));
                    document.getElementById("totalDays").value = totalDays;
                }
            }

            function disableEndDate() {

                var selectedLeaveType = document.getElementById("LeaveType").value;
                var endingDateInput = document.getElementById("endingDate");
                var startingDate = document.getElementById("startingDate");

                if (selectedLeaveType == '1' || selectedLeaveType == '3' || selectedLeaveType == '4' || selectedLeaveType == '5') {
                    endingDateInput.disabled = true;
                    document.getElementById("startingDate").addEventListener("change", function () {
                        calculateTotalDays();
                    });
                }
                else {
                    endingDateInput.disabled = false;
                }
            }

            function clearItems() {

                var startDate = document.getElementById("startingDate");
                var endDate = document.getElementById("endingDate");
                var totalDays = document.getElementById("totalDays");

                if (startDate.value || endDate.value != null) {

                    startDate.value = "";
                    endDate.value = "";
                    totalDays.value = "";
                }
            }


            disableEndDate();

            document.getElementById("LeaveType").addEventListener("change", function (e) {

                e.preventDefault();
                clearItems();
                disableEndDate();
            });

            document.getElementById("endingDate", "startingDate").addEventListener("change", function () {
                calculateTotalDays();
            });
        });

    </script>
}

src/PeopleLink.PL/Web/Areas/Employee/Views/Advance/AllAdvances.cshtml
@{
    ViewBag.Title = "Avans Listesi";
}

@model List<AdvanceViewModel>


<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>Avanslar</h2>
        </div>
    </div>
</div>

<div class="white_shd full margin_bottom_30">
    <div class="full price_table padding_infor_info">
        <div class="details-page">
            <div class="inner_page email_page">
                <div class="midde_cont">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- table section -->
                            <div class="col-md-12">
                                <div class="white_shd full margin_bottom_30">
                                    <div class="full graph_head d-flex justify-content-between">
                                        <div class="heading1 margin_0">
                                            <h2>Avans Talep Listesi <br /></h2>
                                        </div>
                                        <div class="heading1 margin_0">
                                            <a asp-controller="Advance" asp-action="AdvanceRequest" class="btn btn-success">
                                                Avans Talep Et
                                                <i class="fa-solid fa-flus">+</i>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="inbox-body">
                                        <div class="mail-option">
                                            <ul class="nav nav-tabs mb-3 d-flex justifyalign-content-around">
                                                <li class="nav-item">
                                                    <a class="nav-link @(ViewBag.Status == null ? " active" : "")" asp-controller="Advance" asp-action="AllAdvances">Tüm Avanslar</a>
                                                </li>
                                                <li class="nav-item">
                                                    <a class="nav-link @(ViewBag.Status == "Onaylandı." ? "active" : "")" asp-controller="Advance" asp-action="AllAdvances" asp-route-status="Onaylandı.">Onaylananlar</a>
                                                </li>
                                                <li class="nav-item">
                                                    <a class="nav-link @(ViewBag.Status == "Onay bekliyor." ? "active" : "")" asp-controller="Advance" asp-action="AllAdvances" asp-route-status="Onay bekliyor.">Onay Bekleyenler</a>
                                                </li>
                                                <li class="nav-item">
                                                    <a class="nav-link @(ViewBag.Status == "Reddedildi." ? "active" : "")" asp-controller="Advance" asp-action="AllAdvances" asp-route-status="Reddedildi.">Reddedilenler</a>
                                                </li>
                                            </ul>
                                        </div>
                                        @if (ViewBag.HasPendingAdvance != null)
                                        {
                                            <div class="alert alert-danger">@ViewBag.HasPendingAdvance</div>
                                        }
                                        @if (ViewBag.SuccessAdvance != null)
                                        {
                                            <div class="alert alert-success">@ViewBag.SuccessAdvance</div>
                                        }
                                        @if (ViewBag.DeleteSuccessAdvance != null)
                                        {
                                            <div class="alert alert-success">@ViewBag.DeleteSuccessAdvance</div>
                                        }
                                        <table class="table table-inbox table-hover" id="advanceTable">
                                            <thead>
                                                <tr class="text-center">
                                                    <td>Avans Türü</td>
                                                    <td>Tutar</td>
                                                    <td>Para Birimi</td>
                                                    <td>Açıklama</td>
                                                    <td>Talep Tarihi</td>
                                                    <td>Onay Durumu</td>
                                                    <td>Onay Tarihi</td>
                                                    <td></td>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var advance in Model)
                                                {
                                                    <tr class="unread text-center">
                                                        <td class="view-message  dont-show">@Html.DisplayFor(modelItem => advance.AdvanceType)</td>
                                                        <td class="view-message">@advance.Amount</td>
                                                        <td class="view-message inbox-small-cells">@Html.DisplayFor(modelItem => advance.Currency)</td>
                                                        <td>
                                                            @Html.Raw(advance.Description.Length > 10 ? advance.Description.Substring(0, 10) + "..." : advance.Description)
                                                        </td>
                                                        <td class="view-message inbox-small-cells">@advance.RequestDate.ToShortDateString()</td>
                                                        @if ((advance.Status == "Onay Bekliyor."))
                                                        {
                                                            <td class="view-message inbox-small-cells text-warning">@advance.Status</td>
                                                        }
                                                        else if ((advance.Status == "Onaylandı."))
                                                        {
                                                            <td class="view-message inbox-small-cells text-success">@advance.Status</td>
                                                        }
                                                        else
                                                        {
                                                            <td class="view-message inbox-small-cells text-danger">@advance.Status</td>
                                                        }

                                                        @if (advance.ResponseDate != null)
                                                        {
                                                            <td class="view-message inbox-small-cells">@advance.ResponseDate</td>
                                                        }
                                                        else
                                                        {
                                                            <td class="view-message inbox-small-cells">-</td>
                                                        }


                                                        @if (advance.Status == "Onay Bekliyor.")
                                                        {
                                                            <td class="view-message text-white"><a data-remove-item="@advance.Id" id="btnDeleteAdvance" class="btn btn-danger"><i class="fa-solid fa-xmark"></i></a></td>
                                                        }
                                                        else if (advance.Status == "Onaylandı.")
                                                        {
                                                            <td><i class="fa-solid fa-circle-check fa-2x" style="color:#28A745"></i></td>
                                                        }
                                                        else
                                                        {
                                                            <td><i class="fa-solid fa-circle-xmark fa-2x" style="color:#DC3545"></i></td>
                                                        }
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form asp-action="DeleteAdvance" id="frmDeleteAdvance" method="post">
    <input id="hdnAdvanceId" type="hidden" name="advanceId" />
</form>

@section Scripts {
    <script>

        //const advanceTable = document.getElementById('advanceTable');
        //if (advanceTable) {
        //    new simpleDatatables.DataTable(advanceTable);
        //}

        const btnDelete = document.querySelectorAll("#btnDeleteAdvance");
        btnDelete.forEach(button => {
            button.onclick = function (e) {
                e.preventDefault();
                const frmDelete = document.getElementById("frmDeleteAdvance");
                const hdnAdvanceId = document.getElementById("hdnAdvanceId");
                hdnAdvanceId.value = button.getAttribute("data-remove-item");
                frmDelete.submit();
            };

        });

    </script>
} 