src/PeopleLink.PL/Web/Areas/Employee/Models/LeaveViewModel.cs
using ApplicationCore.Enums;
using System.ComponentModel.DataAnnotations;

namespace Web.Areas.Employee.Models
{
    public class LeaveViewModel
    {
        public int Id { get; set; }

        public string EmployeeId { get; set; } = null!;

        [Required(ErrorMessage = "Lütfen başlangıç tarihi seçiniz.")]
        [DisplayFormat(NullDisplayText = "Lütfen bir tarih seçiniz.")]
        public DateTime StartingDate { get; set; }

        [Required(ErrorMessage = "Lütfen bitiş tarihi seçiniz.")]
        [DisplayFormat(NullDisplayText = "Lütfen bir tarih seçiniz.")]
        public DateTime EndingDate { get; set; }

        [Required(ErrorMessage = "Lütfen izin türünü seçiniz.")]
        public LeaveType LeaveType { get; set; }

        public DateTime RequestDate { get; set; }

        public DateTime? ApprovalDate { get; set; }

        [Required(ErrorMessage = "Toplam gün sayısı zorunludur.")]
        [DisplayFormat(NullDisplayText = "Gün sayısı zorunludur.")]
        public int TotalDays { get; set; }

        public string Status { get; set; } = null!;
    }
}

src/PeopleLink.PL/Web/Areas/Employee/Controllers/LeaveController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using ApplicationCore.Specifications.LeaveSpecifications;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.Areas.Employee.Models;

namespace Web.Areas.Employee.Controllers
{
    [Area("Employee")]
    public class LeaveController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly UserManager<ApplicationUser> _userManager;

        public LeaveController(HttpClient httpClient, UserManager<ApplicationUser> userManager)
        {
            _httpClient = httpClient;
            _userManager = userManager;
        }

        public async Task<IActionResult> LeaveRequest()  // İzin talep sayfasına gider
        {
            var user = await _userManager.GetUserAsync(User);
            var leaveTypes = Enum.GetValues(typeof(LeaveType)).Cast<LeaveType>().ToList();

            if (user!.Gender == Gender.Male)
                leaveTypes = leaveTypes.Where(lt => lt != LeaveType.MaternityLeave).ToList();
            else if (user.Gender == Gender.Female)
                leaveTypes = leaveTypes.Where(lt => lt != LeaveType.PaternityLeave).ToList();

            ViewData["UserId"] = user!.Id;
            ViewBag.LeaveTypes = leaveTypes;
            TempData["Picture"] = (await _userManager.GetUserAsync(User))!.PictureUri;
            ViewData["AccruedLeave"] = user.AccruedLeave;
            NameMethod(user);
            return View();

        }



        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> LeaveRequest(LeaveViewModel leaveViewModel)  // Formdan gelen izin verilerini apiye gönderip kaydettirir.
        {
            var user = await _userManager.GetUserAsync(User);
            string apiUrl = $"https://peoplelinkapi1.azurewebsites.net/api/Leave?employeeId={user.Id}";

            var leaves = await _httpClient.GetFromJsonAsync<List<LeaveViewModel>>(apiUrl);
            var leaveTypes = Enum.GetValues(typeof(LeaveType)).Cast<LeaveType>().ToList();

            ViewBag.LeaveTypes = leaveTypes;

            if (ModelState.IsValid)
            {
                if (user!.Gender == Gender.Male)
                    leaveTypes = leaveTypes.Where(lt => lt != LeaveType.MaternityLeave).ToList();
                else if (user.Gender == Gender.Female)
                    leaveTypes = leaveTypes.Where(lt => lt != LeaveType.PaternityLeave).ToList();  

                if (leaves!.Any(l => l.Status == leaveViewModel.Status && l.LeaveType == leaveViewModel.LeaveType))
                {
                    TempData["HasPendingLeave"] = "Onay bekleyen izin talebiniz bulunmaktadır.";
                    return RedirectToAction("AllLeaves");
                }
                else
                {

                    if (leaveViewModel.LeaveType == LeaveType.AnnualLeave)
                    {
                        if (user.AccruedLeave == 0)
                        {
                            TempData["AccuredLeave"] = "Yıllık izin talep edebileceğiniz gün bitmiştir.";
                            ViewData["AccruedLeave"] = user.AccruedLeave;
                            return RedirectToAction("AllLeaves");
                        }
                        else if (leaveViewModel.TotalDays > user.AccruedLeave)
                        {
                            TempData["AccuredLeave"] = "Talep edilen gün sayısı izin hakkınızdan fazladır.";
                            ViewData["AccruedLeave"] = user.AccruedLeave;
                            return RedirectToAction("AllLeaves");
                        }
                        else
                        {
                            user.AccruedLeave = user.AccruedLeave - leaveViewModel.TotalDays;
                        }

                    }
                    var response = await _httpClient.PostAsJsonAsync("https://peoplelinkapi1.azurewebsites.net/api/Leave", leaveViewModel);

                    await _userManager.UpdateAsync(user);
                    TempData["SuccessLeave"] = "İzin talebi başarıyla oluşturuldu.";
                    ViewData["AccruedLeave"] = user.AccruedLeave;
                    NameMethod(user);
                    return RedirectToAction("AllLeaves");
                }
            }

            ViewData["AccruedLeave"] = user.AccruedLeave;
            return View();
        }

        public async Task<IActionResult> AllLeaves(string? status)
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = _userManager.GetUserId(User);
            string apiUrl = $"https://peoplelinkapi1.azurewebsites.net/api/Leave?employeeId={userId}";
            string apiUrlWithStatus = $"https://peoplelinkapi1.azurewebsites.net/api/Leave?approvalStatus={status}&employeeId={userId}";
            TempData["Picture"] = (await _userManager.GetUserAsync(User))!.PictureUri;
            NameMethod(user);
            ViewBag.Status = status;

            if (status != null)
            {
                var leaveWithStatus = await _httpClient.GetFromJsonAsync<List<LeaveViewModel>>(apiUrlWithStatus);
                return View(leaveWithStatus);
            }

            var leaves = await _httpClient.GetFromJsonAsync<List<LeaveViewModel>>(apiUrl);
            return View(leaves);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteLeave(int leaveId)
        {
            var leave = await _httpClient.GetFromJsonAsync<LeaveViewModel>($"https://peoplelinkapi1.azurewebsites.net/api/Leave/{leaveId}");
            var user = await _userManager.GetUserAsync(User);

            user.AccruedLeave = user.AccruedLeave + leave.TotalDays;
            await _userManager.UpdateAsync(user);
            NameMethod(user);
            await _httpClient.DeleteAsync($"https://peoplelinkapi1.azurewebsites.net/api/Leave/{leaveId}");

            TempData["DeleteSuccessLeave"] = "İzin talebi başarıyla silindi.";
            return RedirectToAction("AllLeaves");
        }
        private void NameMethod(ApplicationUser? user)
        {
            TempData["Name"] = user.FirstName + " " + (user.MiddleName != null ? user.MiddleName : "") + (user.MiddleLastName != null ? user.MiddleLastName : "") + " " + user.LastName;
            TempData["Picture"] = user.PictureUri;
        }

    }
}

src/PeopleLink.PL/Web/Areas/Employee/Views/Leave/AllLeaves.cshtml
@model List<LeaveViewModel>
@{
    ViewData["Title"] = "İzinler Sayfası";
}

<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>İzinler</h2>
        </div>
    </div>
</div>

<div class="white_shd full margin_bottom_30">
    <div class="full price_table padding_infor_info">
        <div class="details-page">
            <div class="inner_page email_page">
                <div class="midde_cont">
                    <div class="container-fluid">
                        <div class="row">
                            <!-- table section -->
                            <div class="col-md-12">
                                <div class="white_shd full margin_bottom_30">
                                    <div class="full graph_head d-flex justify-content-between">
                                        <div class="heading1 margin_0">
                                            <h2>İzin Listesi <br /></h2>
                                        </div>
                                        <div class="heading1 margin_0">
                                            <a asp-controller="Leave" asp-action="LeaveRequest" class="btn btn-success">
                                                Yeni İzin Talep Et
                                                <i class="fa-solid fa-flus"></i>
                                            </a>

                                        </div>
                                    </div>
                                    <div class="inbox-body">
                                        <div class="mail-option">
                                            <ul class="nav nav-tabs mb-3 d-flex justifyalign-content-around">
                                                <li class="nav-item">
                                                    <a asp-controller="Leave" asp-action="AllLeaves" class="nav-link @(ViewBag.Status == null ? "active" : "")">Tüm İzinler</a>
                                                </li>
                                                <li class="nav-item">
                                                    <a asp-controller="Leave" asp-action="AllLeaves" asp-route-status="Onaylandı." class="nav-link @(ViewBag.Status == "Onaylandı." ? "active" : "")">Onaylananlar</a>
                                                </li>
                                                <li class="nav-item">
                                                    <a asp-controller="Leave" asp-action="AllLeaves" asp-route-status="Onay Bekliyor." class="nav-link @(ViewBag.Status == "Onay Bekliyor." ? "active" : "")">Onay Bekleyenler</a>
                                                </li>
                                                <li class="nav-item">
                                                    <a asp-controller="Leave" asp-action="AllLeaves" asp-route-status="Reddedildi." class="nav-link @(ViewBag.Status == "Reddedildi." ? "active" : "")">Reddedilenler</a>
                                                </li>
                                            </ul>
                                        </div>
                                        @if (TempData["HasPendingLeave"] != null)
                                        {
                                            <div class="alert alert-danger">@TempData["HasPendingLeave"]</div>
                                        }
                                        @if (TempData["SuccessLeave"] != null)
                                        {
                                            <div class="alert alert-success">@TempData["SuccessLeave"]</div>
                                        }
                                        @if (TempData["DeleteSuccessLeave"] != null)
                                        {
                                            <div class="alert alert-success">@TempData["DeleteSuccessLeave"]</div>
                                        }
                                        @if (TempData["AccuredLeave"] != null)
                                        {
                                            <div class="alert alert-warning">@TempData["AccuredLeave"]</div>
                                        }
                                        <table class="table table-inbox table-hover table-striped" id="leaveTable">

                                            <thead>
                                                <tr class="text-center">
                                                    <th class="view-message ">İzin Türü</th>
                                                    <th class="view-message ">Başlangıç Tarihi</th>
                                                    <th class="view-message ">Biriş Tarihi</th>
                                                    <th class="view-message ">Toplam Gün</th>
                                                    <th class="view-message ">Talep Tarihi</th>
                                                    <th class="view-message ">Onay Durumu</th>
                                                    <th class="view-message">Onay Tarihi</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model)
                                                {
                                                    <tr class="unread text-center">
                                                        <td class="view-message">@Html.DisplayFor(modelItem => item.LeaveType)</td>
                                                        <td class="view-message">@item.StartingDate.ToShortDateString()</td>
                                                        <td class="view-message">@item.EndingDate.ToShortDateString()</td>
                                                        <td class="view-message ms-2">@(item.TotalDays)</td>
                                                        <td class="view-message">@item.RequestDate.ToShortDateString()</td>
                                                        @if ((item.Status == "Onay Bekliyor."))
                                                        {
                                                            <td class="view-message text-warning">@item.Status</td>
                                                        }
                                                        else if ((item.Status == "Onaylandı."))
                                                        {
                                                            <td class="view-message text-success">@item.Status</td>
                                                        }
                                                        else
                                                        {
                                                            <td class="view-message text-danger">@item.Status</td>
                                                        }
                                                        @if (item.ApprovalDate != null)
                                                        {
                                                            <td class="view-message ">@item.ApprovalDate</td>
                                                        }
                                                        else
                                                        {
                                                            <td>-</td>
                                                        }

                                                        @if (item.Status == "Onay Bekliyor.")
                                                        {
                                                            <td class="view-message text-white"><a data-remove-item="@item.Id" id="btnDeleteLeave" class="btn btn-danger"><i class="fa-solid fa-xmark"></i></a></td>
                                                        }
                                                        else if (item.Status == "Onaylandı.")
                                                        {
                                                            <td class="view-message text-white"><i class="fa-solid fa-circle-check" style="color: #38be1e;"></i></td>
                                                        }
                                                        else
                                                        {
                                                            <td class="view-message text-white"><i class="fa-solid fa-circle-xmark" style="color: #ff0000;"></i></td>
                                                        }
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form asp-action="DeleteLeave" id="frmDeleteLeave" method="post">
    <input id="hdnLeaveId" type="hidden" name="leaveId" />
</form>

@section Scripts {
    <script>

        //const leaveTable = document.getElementById('leaveTable');
        //if (leaveTable) {
        //    new simpleDatatables.DataTable(leaveTable);
        //}

        const btnDelete = document.querySelectorAll("#btnDeleteLeave");
        btnDelete.forEach(button => {
            button.onclick = function (e) {
                e.preventDefault();
                const frmDelete = document.getElementById("frmDeleteLeave");
                const hdnLeaveId = document.getElementById("hdnLeaveId");
                hdnLeaveId.value = button.getAttribute("data-remove-item");
                frmDelete.submit();
            };
        });

    </script>
}

src/PeopleLink.PL/Web/Areas/Employee/Views/Leave/LeaveRequest.cshtml
@using ApplicationCore.Enums;

@model LeaveViewModel

@{
    ViewData["Title"] = "İzin Talep Sayfası";
    var userId = ViewData["UserId"];
    var leaveTypes = ViewBag.LeaveTypes;
}

<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>İzinler</h2>
        </div>
    </div>
</div>

<div class="white_shd full margin_bottom_30">
    <div class="full graph_head">
        <h2>İzin Talep Sayfası</h2>
        <div class="full price_table padding_infor_info">
            <hr>
                       <div class="row">
                <div class="col-md-9">
                    <div class="row ">
                        <div class="col-md-9">
                            <form asp-action="LeaveRequest" method="post">
                                <div class="mb-3">
                                    <label asp-for="LeaveType" class="form-label">İzin Türünü Seçiniz</label>
                                    <select asp-for="LeaveType" class="form-control" id="leaveType">
                                        <option value="" disabled selected>Seçiniz</option>
                                        @foreach (var leaveType in leaveTypes)
                                        {
                                            <option value="@((int)leaveType)">@ApplicationCore.Constants.EnumHelper.DisplayName(leaveType)</option>
                                        }
                                    </select>
                                    <span asp-validation-for="LeaveType" class="text-danger"></span>
                                </div>
                                <div class="row">
                                    <div class="col-md-6 mb-3">
                                        <label asp-for="StartingDate" class="form-label">Başlangıç Tarihi</label>
                                        <input id="startingDate" asp-for="StartingDate" type="date" class="form-control" />
                                        <span asp-validation-for="StartingDate" class="text-danger"></span>
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <label asp-for="EndingDate" class="form-label">Bitiş Tarihi</label>
                                        <input id="endingDate" asp-for="EndingDate" type="date" class="form-control" />
                                        <span asp-validation-for="EndingDate" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="mb-3">
                                    <label asp-for="TotalDays" class="form-label">Toplam Gün</label>
                                    <input asp-for="TotalDays" class="form-control" type="text" id="totalDays" />
                                    <span asp-validation-for="TotalDays" class="text-danger"></span>
                                </div>
                                <div class="col-md-6 mb-3">
                                    <input asp-for="EmployeeId" type="hidden" value="@userId" class="form-control" />
                                </div>
                                <div class="col-md-6 mb-3">
                                    <input asp-for="RequestDate" type="hidden" value="@DateTime.Now" class="form-control" />
                                </div>
                                <div class="col-md-6 mb-3">
                                    <input asp-for="ApprovalDate" type="hidden" value="@DateTime.Now.AddDays(2)" class="form-control" />
                                </div>
                                <div class="col-md-6 mb-3">
                                    <input asp-for="Status" type="hidden" value="Onay Bekliyor." class="form-control" />
                                </div>
                                <button id="update-profile-button" type="submit" class="main_bt read_bt w-100 btn btn-lg btn-primary">Talep Et</button>
                            </form>
                        </div>
                        <div class="col-md-3">
                            <div>
                                <label>Kalan Yıllık İzin Gün Sayısı: <strong>@(((int)ViewData["AccruedLeave"]) > 0 ? ((int)ViewData["AccruedLeave"]) : 0)</strong></label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>

        document.addEventListener("DOMContentLoaded", function () {
            var startingDateInput = document.getElementById("startingDate");
            var endingDateInput = document.getElementById("endingDate");
            var totalDays = document.getElementById("totalDays");
            var leaveTypeInput = document.getElementById("leaveType");

            function updateTotalDays() {
                var timeDifference = new Date(endingDateInput.value) - new Date(startingDateInput.value) - 2;
                var totalDays = Math.ceil(timeDifference / (1000 * 3600 * 24));
                document.getElementById("totalDays").value = totalDays;
                console.log(totalDays);
            }

            function setDateLimits() {
                var today = new Date();
                today.setDate(today.getDate() + 1);
                startingDateInput.min = today.toISOString().split("T")[0];
                today.setDate(today.getDate() + 89);
                startingDateInput.max = today.toISOString().split("T")[0];
            }

            function calculateTotalDays() {
                var leaveType = leaveTypeInput.value;
                var startingDate = new Date(startingDateInput.value);
                var endingDate = new Date(startingDate);
                setDateLimits();

                if (leaveType === '1' || leaveType === '3' || leaveType === '4' || leaveType === '5') {
                    endingDateInput.disabled = true;

                    if (leaveType === '1') {
                        var today = new Date();
                        today.setDate(today.getDate() - 7);
                        startingDateInput.min = today.toISOString().split("T")[0];
                        today.setDate(today.getDate() + 14);
                        startingDateInput.max = today.toISOString().split("T")[0];
                        totalDays.value = 3;
                        endingDate.setDate(startingDate.getDate() + 3);
                    } else if (leaveType === '3') {
                        totalDays.value = 3;
                        endingDate.setDate(startingDate.getDate() + 3);
                    } else if (leaveType === '4') {
                        totalDays.value = 112;
                        endingDate.setDate(startingDate.getDate() + 112);
                    } else if (leaveType === '5') {
                        totalDays.value = 5;
                        endingDate.setDate(startingDate.getDate() + 5);
                    }
                    var formattedEndDate = endingDate.toISOString().slice(0, 10);
                    endingDateInput.value = formattedEndDate;
                } else {
                    endingDateInput.disabled = false;
                    setStartingDateLimits();
                    updateTotalDays();
                }

            }

            leaveTypeInput.addEventListener("change", function () {
                clearItems();
                calculateTotalDays();
            });

            startingDateInput.addEventListener("input", function () {
                var startingDate = new Date(startingDateInput.value);
                var endingDate = new Date(startingDate);
                startingDate.setDate(startingDate.getDate() + 1);
                endingDate.setDate(startingDate.getDate() + 10);

                endingDateInput.value = endingDateInput.min;
                endingDateInput.min = startingDate.toISOString().split("T")[0];
                endingDateInput.max = endingDate.toISOString().split("T")[0];
                calculateTotalDays();
            });

            endingDateInput.addEventListener("input", function () {
                updateTotalDays();
            });

            function clearItems() {
                startingDateInput.value = "";
                endingDateInput.value = "";
                totalDays.value = "";
            }

            setDateLimits();
        });

    </script>
}

src/PeopleLink.PL/Web/Areas/Employee/Views/Leave/SuccessView.cshtml
<h1>Post İşlemi Başarılı</h1>